### PR TITLE
added dark mode to credits bar

### PR DESCRIPTION
**Pull request by Chaitanya-087**

### CODE REVIEW

**Comment by Chaitanya-087** [comment]
hi! i found one issue 
like the toggling switch position goes to initial position every time i reload even when the app is in darkmode
i think you need to somehow store the postion of the switch

**Comment by Chaitanya-087** [comment]
ok i'll try

**Comment by Chaitanya-087** [comment]
but plz don't forget to add labels

**Comment by Fonta22** [comment]
Works perfect, thanks for your contribution!!

**Comment by Fonta22** [comment]
> but plz don't forget to add labels
@Chaitanya-087 even that it is not necessary for hacktoberfest to add the label I'll do if you want. 👍🏻

**Comment by Chaitanya-087** [comment]
thank you @Fonta22

**Pull request merged**
