### PR TITLE
Error handling is done for some functions.

### PR DESCRIPTION
**Pull request by LEO1612D**

### CODE REVIEW

**Comment by LEO1612D** [comment]
Currently I am fixing some error related to exception handling

**Comment by Fonta22** [comment]
Nice, thanks for contributing! Tell me when you're done to merge!

**Comment by LEO1612D** [comment]
It's Done it seems working fine on local, but in production on save button there is some issue can you check this changes at your end and let me know if you find something

**Comment by Fonta22** [comment]
Sure, don't worry, I already had issues on the save button

**Comment by Fonta22** [comment]
Everything looks fine, thanks for contributing!

**Pull request merged**
